# Configuration for KG_LFM training with lite dataset

seed: 42

dataset:
  lite: False
  base_path: "/leonardo_scratch/fast/IscrC_KG-LFM/dataset/Tri-Rex_V1"
  graph_embs_base_path: "/leonardo_scratch/fast/IscrC_KG-LFM/dataset/Tri-Rex_V1/graph_embs"
  preload_nodes_embeddings: False

train_conf:
  run_name: "pretrain_trirex"
    
  epochs: 10
  early_stopping_patience: 6
  steps_train: 4000  # Number of training steps before validation
  eval_perc: 0.25

  gradient_accumulation_steps: 16
  clip_grad_norm: 1.0

  learning_rate: 1e-3
  weight_decay: 0.05
  
  checkpoint_dir: "/leonardo_work/IscrC_KG-LFM/checkpoints"
  checkpoint_frequency: 5
  
  resume : True

  dataloader:
    batch_size: 32
    shuffle: True
    num_workers: 2

    include_graphs: True
    return_tensors: "pt"

    pin_memory: False
    persistent_workers: False

model:
  # LLM Configuration
  llm_model_name: "Qwen/Qwen3-8B"
  
  # Graph Encoder Configuration
  graph_pooling: True

  dropout: 0.2  
  num_heads: 4
  num_quantizers: 4
  codebook_size: 128
  shared_codebook: False
  
  # Training Configuration
  tune_language_model: False
  tune_kg_encoder: True
  
  # Graph Node Embedding Configuration
  graph_nodes_embedding_model: "Qwen/Qwen3-Embedding-8B"