seed: 42

dataset:
  name: "trirex"
  lite: True
  base_path: "/leonardo_scratch/fast/IscrC_KG-LFM/dataset/KG_LFM"
  graph_embs_base_path: "/leonardo_scratch/fast/IscrC_KG-LFM/dataset/KG_LFM/graph_embs"
  preload_nodes_embeddings: False

train_conf:
  run_name: "trirex-KG_LFM"
    
  epochs: 10
  early_stopping_patience: 4
  scheduler_patience: 2
  steps_train: 0.5  # 50% of the training set
  eval_perc: 0.5

  gradient_accumulation_steps: 8
  clip_grad_norm: 1.0

  KG_learning_rate: 5e-4
  LLM_learning_rate: 1e-4
  weight_decay: 0.01

  rvq_loss_weight: 0.5
  
  checkpoint_dir: "/leonardo_work/IscrC_KG-LFM/checkpoints"
  checkpoint_frequency: 5
  
  resume : True

  dataloader:
    batch_size: 32
    shuffle: True
    num_workers: 1

    include_graphs: True
    return_tensors: "pt"

    pin_memory: False
    persistent_workers: False

model:
  # LLM Configuration
  llm_model_name: "Qwen/Qwen3-8B"
  
  # Graph Encoder Configuration
  graph_pooling: True

  dropout: 0.2  
  num_heads: 32
  num_quantizers: 16
  codebook_size: 256
  shared_codebook: False
  
  # Training Configuration
  tune_language_model: False
  tune_kg_encoder: True
  
  use_lora: True
  lora_r: 16
  lora_alpha: 32
  lora_target_modules: ["q_proj", "k_proj"]

  # Graph Node Embedding Configuration
  graph_nodes_embedding_model: "Qwen/Qwen3-Embedding-8B"