# Configuration for KG_LFM training with lite dataset

seed: 42

dataset:
  name: "trirex"
  lite: True
  base_path: "/leonardo_scratch/fast/IscrC_KG-LFM/dataset/Tri-Rex_V1"
  graph_embs_base_path: "/leonardo_scratch/fast/IscrC_KG-LFM/dataset/Tri-Rex_V1/graph_embs"
  preload_nodes_embeddings: False

train_conf:
  run_name: "pretrain_trirex_lora"
    
  epochs: 10
  early_stopping_patience: 4

  steps_train: 0.33  # Number of training steps before validation
  eval_perc: 0.5

  gradient_accumulation_steps: 4
  clip_grad_norm: 1.0

  learning_rate: 1e-3
  weight_decay: 0.05
  
  checkpoint_dir: "/leonardo_work/IscrC_KG-LFM/checkpoints"
  checkpoint_frequency: 5
  
  resume : False

  dataloader:
    batch_size: 16

    shuffle: True
    num_workers: 0

    include_graphs: True
    return_tensors: "pt"

    pin_memory: False
    persistent_workers: False

model:
  # LLM Configuration
  llm_model_name: "Qwen/Qwen3-8B"
  
  # Graph Encoder Configuration
  graph_pooling: True

  dropout: 0.2  
  num_heads: 4
  num_quantizers: 10
  codebook_size: 128
  shared_codebook: False
  
  # Training Configuration
  tune_language_model: False
  tune_kg_encoder: True

  use_lora: True
  lora_r: 8
  lora_alpha: 16
  lora_target_modules: ["q_proj", "k_proj"]
  
  # Graph Node Embedding Configuration
  graph_nodes_embedding_model: "Qwen/Qwen3-Embedding-8B"